name: Tests â€“ Plugin CSS

on: [push, pull_request]

jobs:
  plugin-css:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: '20'
      - run: pnpm compile
      - run: pnpm exec vitest run --root . "webpack/plugin-css/"
        working-directory: programs/develop


