name: Tests â€“ Plugin Compilation

on: [push, pull_request]

jobs:
  plugin-compilation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: '20'
      - run: pnpm compile
      - run: pnpm exec vitest run --root .
        working-directory: programs/develop


